-- ============================================================================
-- migrate_to_central.sql
-- ย้าย schema ระบบผลิต จากโปรเจกต์เดิม (dbbhgacstsddonprgiuo)
-- เข้าโปรเจกต์กลาง (syvfdbvmwaeyokytckwb) เพื่อ SSO ร่วมกับแอพอื่น
--
-- พอร์ตตรงจาก live schema เดิม (ดึงด้วย pg_policies/pg_proc/pg_publication/information_schema)
-- - คงชื่อตารางเดิม (ไม่ชนกับ 64 ตารางในกลาง)
-- - RLS/ grants เหมือนเดิมเป๊ะ (ทุกตาราง anon CRUD ได้ ยกเว้น staff = SELECT คอลัมน์ที่ปลอดภัย)
--   จำเป็นสำหรับโหมด PIN kiosk (ใช้ anon key ไม่มี JWT)
-- - รันได้ idempotent (if not exists / drop policy if exists)
-- ⚠️ additive ล้วน — ไม่แตะ 64 ตารางเดิมของกลาง
-- ============================================================================

-- ---------- 1) TABLES ----------

create table if not exists public.staff (
  id           bigint generated by default as identity primary key,
  branch       text,
  name         text,
  role         text default 'operator',
  can_approve  boolean default false,
  email        text,
  pin          text,
  active       boolean default true,
  created_at   timestamptz default now(),
  line_id      text
);
create unique index if not exists staff_line_id_uk on public.staff(line_id) where line_id is not null;

create table if not exists public.machine (
  id          bigint generated by default as identity primary key,
  branch      text not null,
  name        text not null,
  note        text not null default '',
  status      text not null default 'up',
  sort        integer not null default 0,
  updated_at  timestamptz not null default now(),
  unique (branch, name)
);

create table if not exists public.production_ticket (
  id            uuid primary key default gen_random_uuid(),
  branch        text,
  source        text default 'so',
  sonum         text default '',
  from_branch   text,
  so_cover      text default '',
  machine       text default '',
  material_key  text default '',
  label         text default '',
  item_seqs     integer[] default '{}'::integer[],
  oitems        jsonb,
  stage         smallint default 1,
  route         text,
  assignee      text default '',
  priority      integer default 0,
  coil_lot      text default '',
  waste_note    text default '',
  mat_m         numeric default 0,
  prod_m        numeric default 0,
  weight_kg     numeric default 0,
  sheets        integer default 0,
  max_len       numeric default 0,
  people        jsonb default '{}'::jsonb,
  created_by    bigint,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  times         jsonb default '{}'::jsonb
);

create table if not exists public.online_job (
  id          uuid primary key default gen_random_uuid(),
  branch      text not null,
  platform    text not null default '',
  order_no    text not null,
  receiver    text not null default '',
  items       jsonb not null default '[]'::jsonb,
  status      text not null default 'new',
  created_by  bigint references public.staff(id),
  created_at  timestamptz not null default now()
);

create table if not exists public.ticket_event (
  id          bigint generated by default as identity primary key,
  ticket_id   uuid not null references public.production_ticket(id) on delete cascade,
  staff_id    bigint references public.staff(id),
  staff_name  text not null default '',
  action      text not null,
  from_stage  smallint,
  to_stage    smallint,
  detail      text not null default '',
  at          timestamptz not null default now()
);
create index if not exists ticket_event_ticket_idx on public.ticket_event(ticket_id);

create table if not exists public.shape_drawing (
  id          uuid primary key default gen_random_uuid(),
  branch      text not null,
  sonum       text not null,
  seq         integer not null,
  des         text default '',
  segs        jsonb not null default '[]'::jsonb,
  girth_mm    numeric default 0,
  updated_by  text default '',
  updated_at  timestamptz not null default now(),
  unique (branch, sonum, seq)
);

-- ตารางมิเรอร์ ERP (feeder เติมเอง — สร้างโครงว่างไว้)
create table if not exists public.so_live (
  branch      text not null,
  sonum       text not null,
  sodat       date,
  dlvdat      date,
  cuscod      text,
  cusnam      text,
  slmcod      text,
  netamt      numeric default 0,
  docstat     text,
  youref      text,
  synced_at   timestamptz not null default now(),
  primary key (branch, sonum)
);
-- หมายเหตุ: dbbhg เดิมไม่มี ivnum/cancelled_* (ฟีเจอร์ยกเลิก SO ปิดอัตโนมัติ)
-- คงพฤติกรรมเดิม — ถ้าจะเปิดฟีเจอร์ยกเลิก ค่อยเพิ่มคอลัมน์ทีหลัง (add_so_cancel.sql)

create table if not exists public.so_item_live (
  branch      text not null,
  sonum       text not null,
  seq         integer not null,
  stkcod      text,
  stkdes      text,
  ordqty      numeric default 0,
  remqty      numeric default 0,
  unit        text,
  synced_at   timestamptz not null default now(),
  primary key (branch, sonum, seq)
);

create table if not exists public.coil_stock (
  branch      text not null,
  coil_sku    text not null,
  stkdes      text default '',
  totbal      numeric default 0,
  synced_at   timestamptz not null default now(),
  primary key (branch, coil_sku)
);

-- ---------- 2) FUNCTIONS (พอร์ตตรงจาก live) ----------

create or replace function public.verify_pin(p_staff bigint, p_pin text)
returns boolean language sql security definer set search_path to 'public' as $$
  select exists (select 1 from public.staff where id = p_staff and pin = p_pin and active);
$$;

create or replace function public.staff_by_line_id(p_line_id text)
returns table(id bigint, branch text, name text, role text, can_approve boolean, email text, active boolean, line_id text)
language sql security definer set search_path to 'public' as $$
  select s.id, s.branch, s.name, s.role, s.can_approve, s.email, s.active, s.line_id
  from public.staff s where s.line_id = p_line_id and s.active = true;
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

-- triggers updated_at (ตารางที่มี updated_at)
drop trigger if exists trg_touch_machine on public.machine;
create trigger trg_touch_machine before update on public.machine for each row execute function public.touch_updated_at();
drop trigger if exists trg_touch_ticket on public.production_ticket;
create trigger trg_touch_ticket before update on public.production_ticket for each row execute function public.touch_updated_at();
drop trigger if exists trg_touch_shape on public.shape_drawing;
create trigger trg_touch_shape before update on public.shape_drawing for each row execute function public.touch_updated_at();

-- ---------- 3) RLS + GRANTS (พอร์ตตรงจาก live: roles=public/anon+authenticated) ----------

-- ตารางปฏิบัติการ: anon+authenticated CRUD ได้เต็ม (จำเป็นสำหรับ PIN kiosk ที่ใช้ anon key)
do $$
declare t text;
begin
  foreach t in array array['machine','production_ticket','online_job','ticket_event','shape_drawing','so_live','so_item_live','coil_stock']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', t);
    execute format('drop policy if exists %I on public.%I', t||'_all', t);
    execute format('create policy %I on public.%I for all to public using (true) with check (true)', t||'_all', t);
  end loop;
end $$;

-- staff: อ่านได้เฉพาะคอลัมน์ปลอดภัย (pin/line_id อ่านผ่าน RPC เท่านั้น) · ไม่มี policy write → เขียนไม่ได้จาก client
alter table public.staff enable row level security;
drop policy if exists staff_read on public.staff;
create policy staff_read on public.staff for select to public using (true);
revoke all on public.staff from anon, authenticated;
grant select (id, branch, name, role, can_approve, active, email) on public.staff to anon, authenticated;

-- RPC grants
revoke all on function public.verify_pin(bigint, text) from public;
grant execute on function public.verify_pin(bigint, text) to anon, authenticated;
revoke all on function public.staff_by_line_id(text) from public;
grant execute on function public.staff_by_line_id(text) to anon, authenticated;

-- ---------- 4) REALTIME (พอร์ตตรง: machine, so_live, online_job, production_ticket) ----------
do $$
declare t text;
begin
  foreach t in array array['machine','so_live','online_job','production_ticket']
  loop
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
